export enum UserType {
  USER_NAME,
  UNKNOWN_USER_NAME,
  NO_VO_USER_NAME,
  ONE_VO_BALANCE_USER_NAME,
  NEW_USER_NAME,
  REMAND_PRISONER_VISITOR,
  USER_WITH_NO_PRISONERS,
  USER_WITH_PRISONER_ALERTS,
  USER_WITH_PRISONER_RESTRICTIONS,
  USER_WITH_VISITOR_RESTRICTIONS
}
