version: 2.1

orbs:
  hmpps: ministryofjustice/hmpps@9

parameters:
  node-version:
    type: string
    default: 20.12-browsers

jobs:
  build-and-test:
    executor:
      name: hmpps/node
      tag: << pipeline.parameters.node-version >>
    environment:
      INTEG_USER_NAME: ${INTEG_USER_NAME}
      INTEG_PASSWORD: ${INTEG_PASSWORD}
    circleci_ip_ranges: true

    steps:
      - checkout
      - attach_workspace:
          at: ~/app
      - run:
          name: Install missing OS dependency
          command: sudo apt-get install libxss1
      - restore_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
      - run:
          name: Install Dependencies
          command: npm ci --no-audit
      - run:
          name: Install browsers
          command: npx playwright install --with-deps
      - save_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
          paths:
            - node_modules
            - ~/.cache
      - run:
          name: Run Playwright Tests
          command: npm run test:ci
      - store_test_results:
          path: results.xml
      - store_artifacts:
          path: playwright-report/index.html
      - store_artifacts:
          path: test-results

workflows:
  build-and-test:
    jobs:
      - build-and-test
